### ISSUE TITLE
Citing the PPG quality index

### ISSUE THREAD

**Issue by Nusselt24** [MIT-LCP/PhysioNetChallengePublic#2]
Hi, 
I would like to cite the PPG quality index (ppgSQI.m) present in this folder in my paper, but I cannot find any reference to it online.
Could you please give me a suggestion or point me who contact for it?

Sorry to raise a "git issue" for that, but I am not aware of any other way to ask question on git :)

Thank you in advance.

**Comment by cx1111** [comment]
Which folder?

**Comment by Nusselt24** [comment]
this forlder (https://github.com/MIT-LCP/PhysioNetChallengePublic/tree/master/2015/sample-submission)

**Comment by cx1111** [comment]
Sorry about that useless comment before, I thought I was in another github repo. You can just mention it as ppgSQI.m contained in the physionet sample entry. Cite this: http://www.cinc.org/archives/2015/pdf/0273.pdf
